/**
 * LAX card proxy — Thanos backend ↔ LAX / Zypto partner platform.
 *
 * WHY THIS IS SERVER-SIDE: the LAX API key is a SECRET. The wallet apps (mobile,
 * web, extension, desktop) are public + client-side, so a key embedded there is
 * extractable and abusable. Every LAX call is therefore proxied HERE, with
 * LAX_API_KEY read from the environment and never sent to the client. The apps
 * call these endpoints; this router forwards to LAX with the key attached.
 *
 * ARCHITECTURE (corrected 2026-09-02 — see docs/integrations/LAX-INTEGRATION-REQUEST.md
 * for the full writeup): LAX/Zypto is a widget/iframe-driven white-label
 * platform, not a plain REST API — per Zypto's own onboarding guide, "some
 * API calls require a widget (iframe) ID." Nothing here is invented against
 * that model yet because the credentials that drive it don't exist until
 * someone with owner/admin access logs into https://dashboard.lax.money/,
 * creates a Project (type "Custom"), and generates them:
 *   - the dashboard URL ITSELF becomes LAX_API_BASE (self-service — there's
 *     no separate "give us your base URL" step from Zypto)
 *   - a Super Widget (combining per-product child widgets, branded) is
 *     created in-dashboard; its iframe ID is what LAX_WIDGET_ID below will
 *     hold once it exists
 *   - a webhook URL is configured in-dashboard pointing back at this
 *     service — no receiver route exists here yet, needs adding once that
 *     step happens
 *
 * STATUS: SCAFFOLD. Until LAX_API_BASE is configured the routes degrade
 * safely:
 *   • POST /lax/account → hands back the hosted registration URL (lax.money) so
 *     the app's SafePal-style "Create Account → Next" still opens the web flow —
 *     the pre-integration behaviour, but now through the proper server seam.
 *   • the rest return 503 "LAX not configured yet".
 *
 * ENV (set on the VPS `.env`, gitignored — NEVER commit the value):
 *   LAX_API_KEY    — partner secret, generated by the dashboard Project
 *                    (rotate the one shared in chat earlier — that one is
 *                    burned, it was pasted in plaintext)
 *   LAX_API_BASE   — the dashboard-generated Project URL (NOT a fixed,
 *                    documented endpoint — see ARCHITECTURE above)
 *   LAX_WIDGET_ID  — the Super Widget's iframe ID, once created in-dashboard;
 *                    some LAX API calls require this alongside the key
 */
import { Router } from 'express';

const LAX_API_KEY   = process.env.LAX_API_KEY   ?? '';
const LAX_API_BASE  = process.env.LAX_API_BASE  ?? '';
const LAX_WIDGET_ID = process.env.LAX_WIDGET_ID ?? '';
const LAX_PUBLIC_REGISTER = 'https://lax.money';

export const laxRouter = Router();

/** True once the key and base URL are configured — i.e. the real API is
 *  wired. Until then we serve the safe external-registration fallback.
 *  LAX_WIDGET_ID is checked per-route below, not here — not every call is
 *  expected to need it, only whichever ones Zypto's dashboard says do (the
 *  onboarding guide doesn't enumerate which; find out empirically once
 *  configured() is true and cross-reference their support if a call 400s
 *  asking for a widget id we didn't send). */
const configured = (): boolean => Boolean(LAX_API_KEY && LAX_API_BASE);

interface FetchOpts { method?: string; body?: string; headers?: Record<string, string> }

/** Proxy helper — attaches the secret key to a LAX API call. The exact auth
 *  header is still a placeholder (x-api-key vs Bearer …) — Zypto's
 *  onboarding guide covers dashboard setup, not the wire format of calls
 *  made against the resulting Project URL. Confirm against a real response
 *  once LAX_API_BASE is live; a 401 with this header present but wrong
 *  shape is the signal to fix it. */
async function laxFetch(path: string, opts: FetchOpts = {}): Promise<{ status: number; json: unknown }> {
  const res = await fetch(`${LAX_API_BASE}${path}`, {
    method:  opts.method ?? 'GET',
    body:    opts.body,
    headers: {
      'content-type': 'application/json',
      // TODO(lax-live): confirm the auth header name/scheme once LAX_API_BASE
      // is actually configured — untestable before then.
      'x-api-key': LAX_API_KEY,
      ...(LAX_WIDGET_ID ? { 'x-widget-id': LAX_WIDGET_ID } : {}),
      ...(opts.headers ?? {}),
    },
  });
  let json: unknown = null;
  try { json = await res.json(); } catch { /* non-JSON upstream */ }
  return { status: res.status, json };
}

/* POST /lax/account — create account / start registration.
   Body: { address?: string, referralCode?: string }.
   Pre-API: returns the hosted registration URL (with ref/address prefill) so the
   SafePal-style "Next" opens the LAX web flow. Post-API: proxies to LAX and
   returns whatever the native/KYC flow needs (session URL, SDK token, …). */
laxRouter.post('/account', async (req, res) => {
  const { address, referralCode } = (req.body ?? {}) as { address?: string; referralCode?: string };
  if (!configured()) {
    const url = new URL(LAX_PUBLIC_REGISTER);
    if (referralCode) url.searchParams.set('ref', referralCode);
    if (address)      url.searchParams.set('address', address);
    return res.json({ mode: 'external', registrationUrl: url.toString() });
  }
  try {
    // TODO(lax-live): real create-account endpoint + response mapping — confirm against a live Project once one exists.
    const { status, json } = await laxFetch('/account', { method: 'POST', body: JSON.stringify({ address, referralCode }) });
    return res.status(status).json(json);
  } catch {
    return res.status(502).json({ error: 'LAX upstream unreachable' });
  }
});

/* Account/KYC status, card details, top-up — shapes pending the LAX docs. They
   return 503 until configured so the client can show an honest "coming soon". */
laxRouter.get('/account', async (_req, res) => {
  if (!configured()) return res.status(503).json({ error: 'LAX not configured yet' });
  return res.status(501).json({ error: 'not implemented (pending a live LAX dashboard Project)' }); // TODO(lax-live)
});
laxRouter.get('/card', async (_req, res) => {
  if (!configured()) return res.status(503).json({ error: 'LAX not configured yet' });
  return res.status(501).json({ error: 'not implemented (pending a live LAX dashboard Project)' }); // TODO(lax-live)
});
laxRouter.post('/card/topup', async (_req, res) => {
  if (!configured()) return res.status(503).json({ error: 'LAX not configured yet' });
  return res.status(501).json({ error: 'not implemented (pending a live LAX dashboard Project)' }); // TODO(lax-live)
});
