default_platform(:ios)

platform :ios do
  lane :release do
    sh('eas build --platform ios --profile production')
  end
end

platform :android do
  lane :release do
    sh('eas build --platform android --profile production')
  end
end
